CREATE TABLE IF NOT EXISTS CATEGORY (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    VERSION BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS CATEGORY_EVENT_PUBLICATION
(
  ID               UUID NOT NULL,
  EVENT_TYPE       VARCHAR(512) NOT NULL,
  PUBLICATION_DATE TIMESTAMP(9) WITH TIME ZONE NOT NULL,
  SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS PUBLICATION_DATE_IDX
  ON CATEGORY_EVENT_PUBLICATION (PUBLICATION_DATE);
