CREATE TABLE IF NOT EXISTS CATEGORY (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP,
    VERSION BIGINT NOT NULL
);


CREATE TABLE IF NOT EXISTS CATEGORY_EVENT_PUBLICATION
(
  ID               UUID NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  EVENT_TYPE       VARCHAR(512) NOT NULL,
  PUBLICATION_DATE TIMESTAMP(9) WITH TIME ZONE NOT NULL,
  SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS PUBLICATION_DATE_IDX
  ON CATEGORY_EVENT_PUBLICATION (PUBLICATION_DATE);


  CREATE TABLE IF NOT EXISTS ARTICLE (
      ID BIGINT PRIMARY KEY,
      TITLE VARCHAR(255) NOT NULL,
      CATEGORY_ID BIGINT,
      RATING DOUBLE,
      PUBLISHED_AT TIMESTAMP,
      UPDATED_AT TIMESTAMP,
      DELETED_AT TIMESTAMP,
      STATUS INT NOT NULL,
      VERSION BIGINT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS PARAGRAPH (
      ID BIGINT PRIMARY KEY,
      ARTICLE_ID BIGINT NOT NULL,
      ARTICLE_KEY INT,
      TEXT VARCHAR(4000) NOT NULL,
      VERSION BIGINT NOT NULL,
      CONSTRAINT FK_PARAGRAPH_ARTICLE
          FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(ID)
  );

  CREATE TABLE IF NOT EXISTS ARTICLE_EVENT_PUBLICATION
  (
    ID               UUID NOT NULL,
    ARTICLE_ID       BIGINT NOT NULL,
    EVENT_TYPE       VARCHAR(512) NOT NULL,
    PUBLICATION_DATE TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    SERIALIZED_EVENT VARCHAR(4000) NOT NULL,
    PRIMARY KEY (ID)
  );

  CREATE INDEX IF NOT EXISTS PUBLICATION_DATE_IDX
    ON ARTICLE_EVENT_PUBLICATION (PUBLICATION_DATE);
