spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always     # always | embedded | never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      encoding: UTF-8

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.transaction: DEBUG
